[project]
name = "Decentralised_scholarship_fund"
authors = []
description = ""
telemetry = true
requirements = []

[contracts.Decentralised_scholarship_fund]
path = "contracts/Decentralised_scholarship_fund.clar"
depends_on = []

[contracts.improved-scholarship-fund]
path = "contracts/improved-scholarship-fund.clar"
depends_on = []
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
